### ISSUE TITLE
Accessibility issues

### ISSUE THREAD

**Issue by btopro** [oscarsolas/paper-lightbox#11]
- [x] When you select a button to pop open content it doesn't set the focus on the modal so you can still tab behind it
- [x] can't hit the X / escape key to close modal
- [x] multiple modals can be triggered at once getting really lost
- [x] use paper-button instead of <button> for improved UX on mobile / accessibility in general

**Comment by oscarsolas** [comment]
Hi @btopro,
I just created a new release with the improvements that you have proposed.

Thanks!

**Comment by btopro** [comment]
excellent, tested it out now!
